name: Django CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DJANGO_SETTINGS_MODULE: inventory_system.settings
  PYTHON_VERSION: "3.9"
  DATABASE_URL: "sqlite:///db.sqlite3"

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  static-analysis:
    name: Static Code Analysis (Pylint)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: |
          pip install pylint
          pylint **/*.py

  test:
    name: Test Stage (Pytest)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: |
          pip install -r requirements.txt
          pip install pytest
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          pytest tests

  security:
    name: Security Analysis (Bandit)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: |
          pip install bandit
          bandit -r .
