name: Django CI/CD Pipeline
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
env:
  DJANGO_SETTINGS_MODULE: inventory_system.settings
  PYTHON_VERSION: "3.9"
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pylint pylint-django bandit
 
      - name: Run Tests
        run: |
          pytest
 
      - name: Run Pylint for Static Code Analysis
        run: |
          pylint --rcfile=.pylintrc --disable=R,C inventory/ inventory_system/ --fail-under=8.0
 
      - name: Run Bandit for Security Scan
        run: |
           bandit -r inventory/ inventory_system/ -c .bandit.yml --exit-zero