name: Django CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DJANGO_SETTINGS_MODULE: inventory_system.settings
  PYTHON_VERSION: "3.9"

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pylint pylint-django bandit

  lint:
    name: Static Code Analysis (Pylint)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Pylint
        run: pip install pylint pylint-django

      - name: Run Pylint
        run: |
          pylint --rcfile=.pylintrc --disable=R,C inventory/ inventory_system/ --fail-under=8.0

  test:
    name: Test Stage (Pytest)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Pytest
        run: pip install pytest pytest-django

      - name: Run Tests
        run: pytest

  security:
    name: Security Analysis (Bandit)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r inventory/ inventory_system/ -c .bandit.yml --exit-zero
